export const INC_FOLLOWING_COUNT = "INC_FOLLOWING_COUNT";
export const DEC_FOLLOWING_COUNT = "DEC_FOLLOWING_COUNT";
export const EDIT_USER_DETAILS = "EDIT_USER_DETAILS";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
